packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  argon2: set this to true or false
  cpu-features: true
  'nestjs-pino': true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
